#!/usr/bin/env python3
"""Load a Neo4j browser JSON path export back into the local graph.

Reads the JSON produced by a Neo4j Browser "Export JSON" action (array of
path objects), extracts unique nodes and relationships, and replays them via
MERGE statements so the operation is idempotent.

Usage:
    python3 infra/neo4j/scripts/load_json_export.py files/neo4j_query_table_data_2026-6-25.json
    python3 infra/neo4j/scripts/load_json_export.py files/my_export.json --dry-run
    python3 infra/neo4j/scripts/load_json_export.py files/my_export.json --output /tmp/import.cypher
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import subprocess
import sys
import tempfile
from datetime import datetime, timezone

NEO4J_CONTAINER = os.environ.get("NEO4J_CONTAINER", "neo4j-local")
NEO4J_PASSWORD = os.environ.get("NEO4J_PASSWORD", "CambiaEstaClave123!")
NEO4J_DATABASE = os.environ.get("NEO4J_DATABASE", "neo4j")

# Property used as the MERGE key for each node label
MERGE_KEYS: dict[str, str] = {
    "DB2System": "name",
    "DB2Schema": "name",
    "DclgenLibrary": "name",
    "DBTable": "qualifiedName",
    "DclgenArtifact": "qualifiedName",
    "TableColumn": "name",
    "CobolHostField": "name",
}


def _cypher_value(v: object) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        escaped = v.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        return "[" + ", ".join(_cypher_value(i) for i in v) + "]"
    return f"'{str(v)}'"


def _cypher_map(props: dict) -> str:
    parts = [f"{k}: {_cypher_value(v)}" for k, v in props.items()]
    return "{" + ", ".join(parts) + "}"


def _merge_key_for(node: dict) -> tuple[str, str, object]:
    label = node["labels"][0]
    merge_prop = MERGE_KEYS.get(label)
    if not merge_prop:
        raise ValueError(
            f"No MERGE key configured for label '{label}'. "
            f"Add it to MERGE_KEYS in this script."
        )
    return label, merge_prop, node["properties"][merge_prop]


def _collect_graph(data: list[dict]) -> tuple[dict, dict]:
    nodes: dict[str, dict] = {}
    rels: dict[str, dict] = {}
    for item in data:
        for seg in item["path"]["segments"]:
            for n in (seg["start"], seg["end"]):
                nodes.setdefault(n["elementId"], n)
            r = seg["relationship"]
            rels.setdefault(r["elementId"], r)
    return nodes, rels


def generate_cypher(json_path: str, nodes: dict, rels: dict) -> str:
    ts = datetime.now(timezone.utc).isoformat()
    lines: list[str] = [
        f"// Auto-generated by load_json_export.py",
        f"// Source: {json_path}",
        f"// Generated: {ts}",
        f"// Nodes: {len(nodes)}  Relationships: {len(rels)}",
        "",
        "// ── NODES ──────────────────────────────────────────────────────────────",
    ]

    for node in nodes.values():
        label, merge_prop, merge_val = _merge_key_for(node)
        merge_map = f"{{{merge_prop}: {_cypher_value(merge_val)}}}"
        set_map = _cypher_map(node["properties"])
        lines.append(f"MERGE (n:{label} {merge_map}) SET n += {set_map};")

    lines += [
        "",
        "// ── RELATIONSHIPS ───────────────────────────────────────────────────────",
    ]

    skipped = 0
    for rel in rels.values():
        start_node = nodes.get(rel["startNodeElementId"])
        end_node = nodes.get(rel["endNodeElementId"])
        if not start_node or not end_node:
            skipped += 1
            continue
        a_label, a_prop, a_val = _merge_key_for(start_node)
        b_label, b_prop, b_val = _merge_key_for(end_node)
        rel_type = rel["type"]
        props = rel.get("properties", {})
        rel_clause = f"MERGE (a)-[r:{rel_type}]->(b)"
        if props:
            rel_clause += f" SET r += {_cypher_map(props)}"
        lines.append(f"MATCH (a:{a_label} {{{a_prop}: {_cypher_value(a_val)}}})")
        lines.append(f"MATCH (b:{b_label} {{{b_prop}: {_cypher_value(b_val)}}})")
        lines.append(f"{rel_clause};")
        lines.append("")

    if skipped:
        print(f"WARNING: {skipped} relationships skipped (missing endpoint node).", file=sys.stderr)

    return "\n".join(lines)


def run_cypher(cypher: str) -> None:
    with tempfile.NamedTemporaryFile(mode="w", suffix=".cypher", delete=False, encoding="utf-8") as tf:
        tf.write(cypher)
        tmp_path = tf.name

    try:
        with open(tmp_path, encoding="utf-8") as fh:
            result = subprocess.run(
                [
                    "docker", "exec", "-i", NEO4J_CONTAINER,
                    "cypher-shell", "-u", "neo4j", "-p", NEO4J_PASSWORD,
                    "-d", NEO4J_DATABASE, "--non-interactive",
                ],
                stdin=fh,
                capture_output=True,
                text=True,
            )
        if result.returncode != 0:
            print(result.stderr, file=sys.stderr)
            sys.exit(result.returncode)
        if result.stdout.strip():
            print(result.stdout)
    finally:
        pathlib.Path(tmp_path).unlink(missing_ok=True)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Load a Neo4j browser JSON path export into the local Neo4j container."
    )
    parser.add_argument("json_file", help="Path to the Neo4j JSON export file")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated Cypher to stdout without executing it",
    )
    parser.add_argument(
        "--output",
        metavar="FILE",
        help="Write generated Cypher to FILE (and still execute unless --dry-run)",
    )
    args = parser.parse_args()

    json_path = pathlib.Path(args.json_file)
    if not json_path.exists():
        print(f"File not found: {json_path}", file=sys.stderr)
        sys.exit(1)

    with open(json_path, encoding="utf-8") as f:
        data = json.load(f)

    nodes, rels = _collect_graph(data)
    print(f"Loaded {len(nodes)} unique nodes and {len(rels)} unique relationships from export.")

    cypher = generate_cypher(str(json_path), nodes, rels)

    if args.output:
        pathlib.Path(args.output).write_text(cypher, encoding="utf-8")
        print(f"Cypher written to {args.output}")

    if args.dry_run:
        print(cypher)
        return

    print(f"Executing against {NEO4J_CONTAINER}/{NEO4J_DATABASE}...")
    run_cypher(cypher)
    print(f"Done. {len(nodes)} nodes and {len(rels)} relationships merged.")


if __name__ == "__main__":
    main()
